headersOrigin = "config"
redirectsOrigin = "config"
plugins = []

[functions]

[functions."*"]

[build]
publish = "D:\\GitHub\\kided\\dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"

[build.environment]
NODE_VERSION = "18"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/assets/*"

[headers.values]
Cache-Control = "max-age=31536000, immutable"

[[headers]]
for = "*.js"

[headers.values]
Cache-Control = "max-age=31536000, immutable"

[[headers]]
for = "*.css"

[headers.values]
Cache-Control = "max-age=31536000, immutable"

[[headers]]
for = "/index.html"

[headers.values]
Cache-Control = "max-age=0, no-cache, no-store, must-revalidate"

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]